version: '3'
services:
  Emby:
    image: emby/embyserver
    container_name: emby
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $EXTERNAL_HD/.config/embyserver:/config
      - $EXTERNAL_HD/Media:/media
      - /dev/dri/renderD128
    environment:
      - AUTO_UPDATES_ON: 'true'
      - APP_UID: '1000'
      - APP_GID: '1000'
      - GIDLIST: 100,4
    restart: unless-stopped

  Dashboard:
    image: linuxserver/muximux
    container_name: muximux
    environment:
      PGID: '1000'
      PUID;: '1000'
      TZ: America/New_York
    ports:
    - 80:80
    volumes:
    - $EXTERNAL_HD/.config/muximux:/config
    restart: unless-stopped


  CouchPotato:
    image: linuxserver/couchpotato
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/New_York
    stdin_open: true
    volumes:
    - $EXTERNAL_HD/.config/couchpotato:/config
    - $EXTERNAL_HD/couchpotato:/downloads
    - $EXTERNAL_HD/Media/movies:/media/movies
    tty: true
    ports:
    - 5050:5050/tcp
    restart: unless-stopped

  Sonarr:
    image: linuxserver/sonarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/New_York
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - $EXTERNAL_HD/.config/sonarr:/config
    - $EXTERNAL_HD/sonarr:/downloads
    - $EXTERNAL_HD/Media/tv:/media/tv
    tty: true
    ports:
    - 8989:8989
    restart: unless-stopped

  Transmission:
    image: linuxserver/transmission
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/New_York
    stdin_open: true
    volumes:
    - $EXTERNAL_HD/.config/transmission:/config
    - $EXTERNAL_HD/transmission:/media/downloads
    - $EXTERNAL_HD/transmission/watch:/watch
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
