version: '3'
services:
  Emby:
    image: emby/embyserver
    container_name: emby
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - $EXTERNAL_HD/emby:/config
      - $EXTERNAL_HD/media:/media
      - $EXTERNAL_HD/downloads:/downloads
      - /dev/dri/renderD128
    environment:
      - APP_UID=$UID
      - APP_GID=$GID
      - UNMASK=002
      - GIDLIST=100,4
    restart: unless-stopped

  Dashboard:
    image: linuxserver/muximux
    container_name: muximux
    environment:
      PGID: $GID
      PUID: $UID
      UNMASK: 022
      TZ: America/New_York
    ports:
      - 8000:80
    volumes:
      - $EXTERNAL_HD/muximux:/config
    restart: unless-stopped

  Radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      PGID: $GID
      PUID: $UID
      UNMASK: 022
      TZ: America/New_York
    stdin_open: true
    volumes:
      - $EXTERNAL_HD/radarr:/config
      - $EXTERNAL_HD/downloads:/downloads
      - $EXTERNAL_HD/media/movies:/movies
    tty: true
    ports:
      - 7878:7878
    restart: unless-stopped

  Sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PGID: $GID
      PUID: $UID
      UNMASK: 022
      TZ: America/New_York
    stdin_open: true
    volumes:
      - $EXTERNAL_HD/sonarr:/config
      - $EXTERNAL_HD/downloads:/downloads
      - $EXTERNAL_HD/media/tv:/tv
      - $EXTERNAL_HD/media:/media
    tty: true
    ports:
      - 8989:8989
    restart: unless-stopped

  Deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      PGID: $GID
      PUID: $UID
      UNMASK: 022
      TZ: America/New_York
    stdin_open: true
    volumes:
      - $EXTERNAL_HD/deluge:/config
      - $EXTERNAL_HD/downloads:/downloads
      - $EXTERNAL_HD/media/movies:/movies
      - $EXTERNAL_HD/media/tv:/tv
      - $EXTERNAL_HD/deluge/watch:/watch
    ports:
      - 58846:58846
      - 8112:8112
    expose:
      - "53160"
      - "53160/udp"
    restart: unless-stopped